//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.cart = new HashSet<cart>();
            this.order_details = new HashSet<order_details>();
        }

        [Key]
        public int productId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please select the category")]
        public int fk_categoryId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the product name")]
        public string productName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the product price")]
        public double productPrice { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the product quantity")]
        public int productQty { get; set; }
        public string productImage { get; set; }
        [DataType(DataType.Upload)]
        [Display(Name = "Upload Image")]
        public string productImageFile { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the product description")]
        public string productDesc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> cart { get; set; }
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
